volumes:
  postgres_data:
    name: litellm_volume

services:
  postgresDB:
    image: debezium/postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellmproxy
      POSTGRES_PASSWORD: dbpassword9090
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fi-mcp-dev:
    build:
      context: ./fi-mcp-dev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FI_MCP_PORT=8080

  litellm:
    image: ghcr.io/berriai/litellm:main-v1.73.0-nightly
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://litellmproxy:dbpassword9090@postgres:5432/litellm"
      STORE_MODEL_IN_DB: "True"
      OPENAI_API_KEY: dummy_key
      LITELLM_MASTER_KEY: "sk-1234"
      LITELLM_SALT_KEY: "sk-1234"  
      LITELLM_PORT: "4000"
    depends_on:
      - postgresDB
