litellm_settings:
  drop_params: true  # optionally remove unsupported parameters
  set_verbose: false  # set verbose mode for debugging
  # default_timeout: 60
  request_timeout: 6000
  litellm_proxy_port: 4000

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
