name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Setup Nix environment
      run: nix develop --command echo "Nix environment ready"
    
    - name: Run tests
      run: nix develop --command just test
    
    - name: Run linting
      run: nix develop --command just lint